server:
  port: 8080

spring:
  application:
    name: short-url-server
  datasource:
    url: jdbc:mysql://localhost:13306/shorturl_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      url: redis://localhost:55000
      database: 0


mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true