server:
  port: 8080

spring:
  application:
    name: short-url-server
  datasource:
    url: jdbc:mysql://localhost:3306/shorturl_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
  data:
    redis:
      host: localhost
      port: 6379


mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true